#!/usr/bin/env python
# Copyright 2026 Brainchip Holdings Ltd.  Apache 2.0 License
"""Summary scatter plots for the README: accuracy against hardware cost.

Two panels, one per cost measure -- latency and energy per inference -- both
plotted against Akida top-1 accuracy, for all six models.

Points only, deliberately. Three widely spaced widths per resolution is far too
few to justify joining: a straight segment between two of them asserts a linear
trade-off that was never measured, and reading the vertical gap between two such
segments invents a difference between the resolutions that the data does not
support.

Hardware figures are taken from the ``HwPr`` mapping mode, which is the fastest
and the lowest-energy of the three modes on every model here. Everything is read
from ``docs/metrics.json``, so this stays in step with the tables it sits above:
it is regenerated by ``update_readme.py``.

Example
-------
    python imagenet_akidanet_summary_plot.py
"""
import json
import pathlib

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# Mapping mode the summary is drawn from. The tables carry all three; this plot
# shows the one worth deploying.
MAP_MODE = 'hwpr'

# Series are the two input resolutions, in fixed order -- colour follows the
# resolution, never its rank in the data. Marker shape repeats the distinction so
# identity never rests on colour alone.
# 'label_dy' pushes each series' point labels to opposite sides, which is what
# keeps them apart where points of the two series land close together.
SERIES = [
    {'resolution': 224, 'color': '#2a78d6', 'marker': 'o', 'label': '224 x 224 input',
     'label_dy': 11},
    {'resolution': 160, 'color': '#eb6834', 'marker': 's', 'label': '160 x 160 input',
     'label_dy': -19},
]
ALPHAS = [0.25, 0.5, 1.0]

SURFACE = '#fcfcfb'
INK = '#0b0b0b'
INK_MUTED = '#52514e'
GRID = '#dcdcd8'

PANELS = [
    {'field': 'latency_ms', 'xlabel': 'Latency (ms per inference)',
     'title': 'Accuracy against latency'},
    {'field': 'total_E', 'xlabel': 'Total energy (mJ per inference)',
     'title': 'Accuracy against energy'},
]


def _prefix(alpha, resolution):
    """Metrics key prefix for one model. Mirrors model.metrics_prefix()."""
    return f'a{int(alpha * 100)}_{resolution}_'


def _value(metrics, key):
    """Read a metrics value as a float, tolerating the trailing '%' on accuracies."""
    return float(metrics[key].rstrip('%').replace(',', ''))


def plot_summary(metrics, savepath=None):
    """Plot accuracy against latency and against energy, for every model.

    Args:
        metrics:  parsed docs/metrics.json.
        savepath: if given, save the figure to this path (PNG).

    Returns:
        matplotlib Figure.
    """
    fig, axs = plt.subplots(1, 2, figsize=(11, 4.6), constrained_layout=True)
    fig.patch.set_facecolor(SURFACE)

    for ax, panel in zip(axs, PANELS):
        ax.set_facecolor(SURFACE)
        x_max = 0.0
        for series in SERIES:
            xs, ys = [], []
            for alpha in ALPHAS:
                prefix = _prefix(alpha, series['resolution'])
                xs.append(_value(metrics, f'{prefix}{MAP_MODE}_{panel["field"]}'))
                ys.append(_value(metrics, f'{prefix}akida_t1'))
            x_max = max(x_max, max(xs))

            ax.plot(xs, ys, color=series['color'], marker=series['marker'],
                    markersize=10, linestyle='none', markeredgecolor=SURFACE,
                    markeredgewidth=1.5, label=series['label'], zorder=3)

            # Direct-label each point with its width multiplier -- three per
            # series, so this identifies the models without becoming clutter.
            # The end points are anchored inwards so they cannot run off the axes.
            for i, (alpha, x, y) in enumerate(zip(ALPHAS, xs, ys)):
                ha = 'left' if i == 0 else ('right' if i == len(ALPHAS) - 1 else 'center')
                dx = {'left': -6, 'right': 6, 'center': 0}[ha]
                ax.annotate(f'alpha {alpha}', (x, y), textcoords='offset points',
                            xytext=(dx, series['label_dy']), ha=ha, fontsize=10,
                            color=INK_MUTED, zorder=4)

        ax.set_xlabel(panel['xlabel'], fontsize=12, color=INK)
        ax.set_title(panel['title'], fontsize=13, color=INK, loc='left', pad=10)
        ax.set_xlim(-0.04 * x_max, 1.06 * x_max)
        ax.set_ylim(37, 76)
        ax.grid(True, color=GRID, linewidth=0.8, zorder=0)
        ax.set_axisbelow(True)
        ax.tick_params(labelsize=11, colors=INK_MUTED)
        for side in ('top', 'right'):
            ax.spines[side].set_visible(False)
        for side in ('left', 'bottom'):
            ax.spines[side].set_color(GRID)

    axs[0].set_ylabel('Akida top-1 accuracy (%)', fontsize=12, color=INK)
    axs[0].legend(loc='lower right', fontsize=11, frameon=True,
                  facecolor=SURFACE, edgecolor=GRID, labelcolor=INK)

    fig.suptitle('AkidaNet on ImageNet: accuracy against hardware cost '
                 '(AKD1500, HwPr mapping)',
                 fontsize=14, fontweight='bold', color=INK)

    if savepath is not None:
        fig.savefig(savepath, dpi=150, facecolor=SURFACE)

    return fig


if __name__ == '__main__':
    here = pathlib.Path(__file__).parent
    metrics = json.loads((here / 'docs' / 'metrics.json').read_text())
    out = here / 'docs' / 'ref_benchmark_summary.png'
    plot_summary(metrics, savepath=out)
    print(f'Summary plot written to {out}')
